services:
  - type: web
    name: yurak-urishi
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.2
